<div class="container">
    <div class="row">
        <div class="col-md-12">
            <!-- 轮播 -->
            <div id="myCarousel" class="carousel slide" data-ride="carousel">
                <!-- 轮播（Carousel）指标 -->
                <ol class="carousel-indicators">
                    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                    <li data-target="#myCarousel" data-slide-to="1"></li>
                    <li data-target="#myCarousel" data-slide-to="2"></li>
                </ol>
                <!-- 轮播（Carousel）项目 -->
                <div class="carousel-inner">
                    <div class="item slide1">
                        <!-- <img src="img/slide-1.png" alt="First slide"> -->
                    </div>
                    <div class="item slide2">
                        <!-- <img src="img/slide-2.png" alt="Second slide"> -->
                    </div>
                    <div class="item active slide3">
                        <!-- <img src="img/slide-3.png" alt="Third slide"> -->
                    </div>
                </div>
            </div>
        </div>
    </div>
    <p style="border-bottom: 2px solid #B1B1B1;margin-top:50px;margin-bottom:20px;">联系我们</p>
    <p>北京林业大学</p>
    <span><b>地址：</b></span><span>北京市海淀区清华东路35号西配楼311</span><br>
    <span><b>邮政编码：</b></span><span>100083</span><br>
    <span><b>Email:</b></span><span>senlinren@bjfu.edu.cn</span><br>
    <span><b>电话：</b></span><span>010-62336651</span><br>
</div>