
                                <!--<li><a href="intro_duce.htm">➣ 团队简介</a></li>
                                <li><a href="intro_teacher.htm">➣ 师资力量</a></li>
                                <li><a href="intro_culture.htm">➣ 团队文化</a></li>
                                <li><a href="intro_team.htm">➣ 团队结构</a></li>
                                <li><a href="intro_public.htm">➣ 公众号</a></li>-->
                                <li><a href="[field:typeurl/]">➣ [field:typename/]</a></li>
                             