                <div class="row">
                <div class="col-md-3 co_title enroll_title">
                    <span>&nbsp;</span><p>报名表</p>
                </div>
                </div>
                <div class="enroll_div">
                    <img src="../templets/senlinren/images/enroll-icon.png" style="height:50px;">
                    <span class="enroll_line">&nbsp;</span>
                    <img src="../templets/senlinren/images/enrollQRcode.png" style="height:200px;">
                    <span class="enroll_tip">扫码报名森林人</span>
                </div>