                <div class="teamintro_div">
                    <img src="../templets/senlinren/images/big-logo.png" />
                    <p id="teamintro_title">森林人只培养IT领袖和行业精英！</p>
                    <p>森林人让你的人生有更多可能</p>
                    <p>不需要你有坚实的专业基础</p>
                    <p>只要你怀揣梦想、富有激情</p>
                    <p>就来加入我们吧！</p>
                </div>
                <br/>
                <br/>