<div class="intro-content">
                    <p class="title">团队文化综述</p>
                    <p class="content">森林人团队以培养队员高尚的道德情操、优秀的工作作风和扎实的专业技能为目标，将导师制、科研团队及工程实践相结合，通过“干中学”的方式，以科研课题为牵引，选拔优秀学生直接参与科研活动，让队员的创新能力和综合素质有较大提高，将高校人才培养与社会需求无缝对接，同时为高层次精英培养提供人才储备。</p>
                    <div class="content-teamfamily"><center><img src="/templets/senlinren/images/teamfamily.png"></center></div>
                    <p class="sub-title">培养过程</p>
                    <p class="content"><pre>
1.孵化对象的选择 
        1.北京林业大学全日制在校学生
        2.较好的综合素质，良好的组织纪律性，具有团队合作精神。
2.孵化步骤 
        1.先进入预备队，在老师和组长的安排和指导下进行培训和实习
        2.合格者正式进入一线，参与科研项目。不合格者淘汰
3.孵化完成及成功的标志 
        1.凡在团队参与一线工作直至本科或研究生毕业者，或一线工作期间有突出贡献者，视为孵化完成
        2.队员毕业离校后，若受到用人单位或深造单位的好评，则视为孵化成功</pre></p>
        <hr>
        <p class="sub-title">口号与文化</p>
        <p class="content"><pre>
森林人只培养行业领袖与IT精英
森林人是精益求精的项目团队
森林人是阳光向上的精英联盟
森林人是以研促产的教育机构

无论是你初出茅庐、涉世未深的大一新生
亦或是学富五车、身经百战的青年才俊
只要你怀揣梦想、富有激情、热爱学习
森林人都会为你提供量身定制的平台

在这里你将获取
与科学家、工程师比肩，参与与时俱进的精锐项目
与艺术家、设计师同堂，畅享妙趣横生的学术讲座
一个足够让你骄傲，让人倾慕的人生阅历
与一份与你付出相匹配的薪酬

都快来加入我们吧
森林人让你的未来多一种可能
            </pre></p>
            <hr>
        <p class="sub-title">致敬</p>
        <p class="content">森林人团队得到华中科技大学Dian团队刘玉教授的指导与帮助，特在此致敬！</p>
        <p class="content"><strong>团队网址链接：<a href="http://dian.hust.edu.cn" target="_blank" style="text-decoration:underline">http://dian.hust.edu.cn</a></strong></p>
                </div>