<div class="container">
	<div class="row">
		<div class="col-md-12">
			<!-- 轮播 -->
			<div class="carousel slide" data-ride="carousel" id="myCarousel">
				<!-- 轮播（Carousel）指标 -->
				<ol class="carousel-indicators">
					<li class="active" data-slide-to="0" data-target="#myCarousel">
						&nbsp;</li>
					<li data-slide-to="1" data-target="#myCarousel">
						&nbsp;</li>
					<li data-slide-to="2" data-target="#myCarousel">
						&nbsp;</li>
				</ol>
				<!-- 轮播（Carousel）项目 -->
				<div class="carousel-inner">
					<div class="item active slide4">
						<!-- <img src="img/slide-1.png" alt="First slide"> --></div>
					<div class="item slide5">
						<!-- <img src="img/slide-2.png" alt="Second slide"> --></div>
					<div class="item slide6">
						<!-- <img src="img/slide-3.png" alt="Third slide"> --></div>
				</div>
			</div>
		</div>
	</div>
	
</div>

<br><br>

<!-- 诚邀合作、利益共享 -->
<div class="container project">
    <div class="row">
        <div class="col-md-3 co_title">
			<span>&nbsp;</span><p>诚邀合作、利益共享</p>
		</div>
    </div>
    <div class="co_content">
        <span>实力</span><br><br>
        <p>精英战队、高教黄埔。森林人团队做为北京林业大学的专业化研发团队，承担过国土、军工、通讯、园林、动画、交互等众多领域，拥有强大的技术团队，我们值得信赖！</p>
        <span>共享</span><br><br>
        <p>资源共建、战略共享。森林人与您共建战略共享资源平台，共同承担产业项目，彼此共赢，共同发展，共同进步！</p>
        <span>理念</span><br><br>
        <p>以产促研，永续发展。森林人团队秉持“携手伙伴，开创共赢发展新局”的理念，共同开展政企、企企、产学研合作，实现互惠互利、共同发展，参与推动行业合作平台建设，推动行业发展与进步！</p>
        <span>目标</span><br><br>
        <p>精诚方略，志在千里。森林人团队同您一道打造国内领先的优质产品。</p>
    </div>
</div>