<div class="container">
	<div class="row">
		<div class="col-md-12">
			<!-- 轮播 -->
			<div class="carousel slide" data-ride="carousel" id="myCarousel">
				<!-- 轮播（Carousel）指标 -->
				<ol class="carousel-indicators">
					<li class="active" data-slide-to="0" data-target="#myCarousel">
						&nbsp;</li>
					<li data-slide-to="1" data-target="#myCarousel">
						&nbsp;</li>
					<li data-slide-to="2" data-target="#myCarousel">
						&nbsp;</li>
				</ol>
				<!-- 轮播（Carousel）项目 -->
				<div class="carousel-inner">
					<div class="item slide1">
						<!-- <img src="img/slide-1.png" alt="First slide"> --></div>
					<div class="item slide2">
						<!-- <img src="img/slide-2.png" alt="Second slide"> --></div>
					<div class="item active slide3">
						<!-- <img src="img/slide-3.png" alt="Third slide"> --></div>
				</div>
			</div>
		</div>
	</div>
</div>
