<div class="container">
	<div class="row">
		<div class="col-md-12">
			<!-- 轮播 -->
			<div class="carousel slide" data-ride="carousel" id="myCarousel">
				<!-- 轮播（Carousel）指标 -->
				<ol class="carousel-indicators">
					<li class="active" data-slide-to="0" data-target="#myCarousel">
						&nbsp;</li>
					<li data-slide-to="1" data-target="#myCarousel">
						&nbsp;</li>
					<li data-slide-to="2" data-target="#myCarousel">
						&nbsp;</li>
				</ol>
				<!-- 轮播（Carousel）项目 -->
				<div class="carousel-inner">
					<div class="item active slide4">
						<!-- <img src="img/slide-1.png" alt="First slide"> --></div>
					<div class="item slide5">
						<!-- <img src="img/slide-2.png" alt="Second slide"> --></div>
					<div class="item slide6">
						<!-- <img src="img/slide-3.png" alt="Third slide"> --></div>
				</div>
			</div>
		</div>
	</div>
</div>
<br />
<br />
<!-- 项目展示 -->
<div class="container project" id="projectList">
	<div class="row">
		<div class="col-md-12 title" style="padding-left: 15px;">
			<p>
				项目展示</p>
		</div>
	</div>
	<p class="currentProject">
		当前项目：<span>15</span></p>
	<div class="row">
		<div class="col-md-12">
			<div class="table-responsive">
				<table class="table table-bordered table-striped table-hover">
					<thead>
						<tr>
							<th>
								编号</th>
							<th>
								项目名称</th>
							<th>
								项目类型</th>
							<th>
								项目来源</th>
							<th>
								完成时间</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>
								01</td>
							<td>
								好乐通一体化通信系统</td>
							<td>
								通信系统</td>
							<td>
								好乐通科技有限公司</td>
							<td>
								&nbsp;</td>
						</tr>
						<tr>
							<td>
								02</td>
							<td>
								Getword专业抓词引擎</td>
							<td>
								应用软件</td>
							<td>
								北京如令科技有限公司</td>
							<td>
								&nbsp;</td>
						</tr>
						<tr>
							<td>
								03</td>
							<td>
								点点成长app</td>
							<td>
								应用软件</td>
							<td>
								&nbsp;</td>
							<td>
								&nbsp;</td>
						</tr>
						<tr>
							<td>
								04</td>
							<td>
								某部队飞艇控制系统</td>
							<td>
								应用软件</td>
							<td>
								人民解放军某部队</td>
							<td>
								&nbsp;</td>
						</tr>
						<tr>
							<td>
								05</td>
							<td>
								阿福公益app</td>
							<td>
								应用软件</td>
							<td>
								中国妇女发展基金会蓝玫瑰基金会</td>
							<td>
								&nbsp;</td>
						</tr>
						<tr>
							<td>
								06</td>
							<td>
								兰苑&mdash;基于移动终端的园林景观演示系统</td>
							<td>
								游戏软件</td>
							<td>
								国家级大学生科技创新项目</td>
							<td>
								2016.6</td>
						</tr>
						<tr>
							<td>
								07</td>
							<td>
								智能空中感知平台</td>
							<td>
								动画模拟</td>
							<td>
								北京航空航天大学</td>
							<td>
								2016.3</td>
						</tr>
						<tr>
							<td>
								08</td>
							<td>
								&ldquo;橘中戏3.0&rdquo;的设计、实践与产品化策略研究</td>
							<td>
								游戏软件</td>
							<td>
								教育部人文社科项目</td>
							<td>
								2015.12</td>
						</tr>
						<tr>
							<td>
								09</td>
							<td>
								Zombies and hunters</td>
							<td>
								游戏软件</td>
							<td>
								声色传媒</td>
							<td>
								2015.12</td>
						</tr>
						<tr>
							<td>
								10</td>
							<td>
								数字园林景观展示系统</td>
							<td>
								仿真模拟</td>
							<td>
								教育部人文社科项目</td>
							<td>
								2014.7</td>
						</tr>
						<tr>
							<td>
								11</td>
							<td>
								《橘中戏2.0》App的设计与实践</td>
							<td>
								游戏软件</td>
							<td>
								教育部人文社科项目</td>
							<td>
								2013.12</td>
						</tr>
						<tr>
							<td>
								12</td>
							<td>
								运动捕捉技术在三维动画中的应用研究</td>
							<td>
								动画模拟</td>
							<td>
								教育部人文社科项目</td>
							<td>
								2012.5</td>
						</tr>
						<tr>
							<td>
								13</td>
							<td>
								&ldquo;书游纪&rdquo;国学益智类3D游戏软件</td>
							<td>
								仿真模拟</td>
							<td>
								国家级大学生科技创新项目</td>
							<td>
								2011.10</td>
						</tr>
						<tr>
							<td>
								14</td>
							<td>
								数字化群众游行表演仿真模拟</td>
							<td>
								仿真模拟</td>
							<td>
								建国60周年大庆组委会</td>
							<td>
								2009.9</td>
						</tr>
						<tr>
							<td>
								15</td>
							<td>
								IBM虚拟全球会议室</td>
							<td>
								仿真模拟</td>
							<td>
								IBM 中国创新中心</td>
							<td>
								2007.9</td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
	</div>
	<div class="row page">
		<div class="col-md-12">
			<p>
				<span>&lt;</span><span>1</span><span>&gt;</span>共1页</p>
		</div>
	</div>
</div>
