<div class="row">
                    <div class="col-md-3 co_title enroll_title">
                        <span>&nbsp;</span><p>常见问题与回答</p>
                    </div>
                </div>
                <p><b>1.提交报名表出现错误，无法成功提交报名表</b></p>
                <p style="margin-left:12px;">请首先检查您填写的信息是否正确。若仍有问题，请在“常见问题与回答”页面留言，我们会尽快处理您的报名信息。或者发送邮件到hr@dian.org.cn</p>
                <p><b>2.我想加入森林人团队，但是担心自己的技术达不到森林人的要求</b></p>
                <p style="margin-left:12px;margin-bottom:200px;">森林人团队在招新时，关注的不仅仅是新人的技术基础，还会着重考察新人的态度，及对森林人团队文化的认同度。“缺乏技术基础”，不等于你不是我们想要的人。</p>