<div style="margin-right: 10px;border-bottom:1px solid #ccc;margin-bottom:10px;">
                    <p style="	display:inline-block;	width:250px;margin: 0 auto;overflow: hidden;	text-overflow: ellipsis;	white-space: nowrap;">➣&nbsp;&nbsp;<a href="[field:arcurl/]">[field:title/]</a></p>
                    <p style="	display:inline-block;	margin: 0 auto;float:right;color:#326331;">[field:pubdate function="GetDateTimeMK(@me)" /]</p>
                </div>