<?php
$z[0]=Array("global","",824,856);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",1014,1046);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",1096,1128);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",1542,1574);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",1891,1918);
$z[4][4]['name']="cfg_basehost";
$z[5]=Array("global","",2140,2167);
$z[5][4]['name']="cfg_basehost";

?>