<?php
$z[0]=Array("global","",74,100);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",601,633);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",701,733);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("include","",1037,1072);
$z[3][4]['filename']="head.htm";
$z[4]=Array("arclist","\r\n                <div style=\"margin-right: 10px;border-bottom:1px solid #ccc;margin-bottom:10px;margin-left: -70px;\">\r\n                    <p style=\"	display:inline-block;	width:350px;margin: 0 auto;overflow: hidden;	text-overflow: ellipsis;	white-space: nowrap;\">➣&nbsp;&nbsp;<a href=\"[field:arcurl/]\">[field:title/]</a></p>\r\n                    <p style=\"	display:inline-block;	margin: 0 auto;float:right;color:#326331;\">[field:pubdate function=\"GetDateTimeMK(@me)\" /]</p>\r\n                </div>\r\n                ",5615,6231);
$z[4][4]['row']="5";
$z[4][4]['typeid']="7";
$z[4][4]['titlelen']="100";
$z[4][4]['orderby']="pubdate";
$z[4][4]['orderway']="desc";
$z[5]=Array("global","",6309,6336);
$z[5][4]['name']="cfg_basehost";
$z[6]=Array("include","",18364,18401);
$z[6][4]['filename']="footer.htm";

?>