<?php
$z[0]=Array("global","",69,95);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",587,619);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",686,718);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("include","",6041,6076);
$z[3][4]['filename']="head.htm";
$z[4]=Array("arclist","\n                <div style=\"margin-right: 10px;border-bottom:1px solid #ccc;margin-bottom:10px;margin-left: -70px;\">\n                    <p style=\"	display:inline-block;	width:350px;margin: 0 auto;overflow: hidden;	text-overflow: ellipsis;	white-space: nowrap;\">➣&nbsp;&nbsp;<a href=\"[field:arcurl/]\">[field:title/]</a></p>\n                    <p style=\"	display:inline-block;	margin: 0 auto;float:right;color:#326331;\">[field:pubdate function=\"GetDateTimeMK(@me)\" /]</p>\n                </div>\n                ",10522,11133);
$z[4][4]['row']="5";
$z[4][4]['typeid']="7";
$z[4][4]['titlelen']="100";
$z[4][4]['orderby']="pubdate";
$z[4][4]['orderway']="desc";
$z[5]=Array("global","",11208,11235);
$z[5][4]['name']="cfg_basehost";
$z[6]=Array("include","",23023,23060);
$z[6][4]['filename']="footer.htm";

?>