<?php
$z[0]=Array("global","",74,100);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",601,633);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",701,733);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("include","",776,811);
$z[3][4]['filename']="head.htm";
$z[4]=Array("arclist","\r\n                    <li>\r\n                        <a href=\"[field:typeurl/]\" title=\"[field:fulltitle/]\">[[field:typename/]]</a>&nbsp;\r\n                        <a href=\"[field:arcurl /]\">[field:title /]&nbsp;...</a>\r\n                    </li>\r\n                    ",5362,5724);
$z[4][4]['row']="3";
$z[4][4]['typeid']="21";
$z[4][4]['titlelen']="42";
$z[4][4]['orderby']="pubdate";
$z[4][4]['orderway']="desc";
$z[5]=Array("arclist","\r\n                    <li>\r\n                        <a href=\"[field:typeurl/]\" title=\"[field:fulltitle/]\">[[field:typename/]]</a>&nbsp;\r\n                        <a href=\"[field:arcurl /]\">[field:title /]&nbsp;...</a>\r\n                    </li>\r\n                    ",5858,6220);
$z[5][4]['row']="3";
$z[5][4]['typeid']="22";
$z[5][4]['titlelen']="42";
$z[5][4]['orderby']="pubdate";
$z[5][4]['orderway']="desc";
$z[6]=Array("global","",6321,6348);
$z[6][4]['name']="cfg_basehost";
$z[7]=Array("include","",13316,13353);
$z[7][4]['filename']="footer.htm";

?>