<?php
$z[0]=Array("global","",70,96);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",588,620);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("include","",913,948);
$z[2][4]['filename']="head.htm";
$z[3]=Array("list","\n            <div class=\"list_article_div\">\n                <p class=\"list_article_p1\">➣&nbsp;&nbsp;<a href=\"[field:arcurl/]\">[field:title/]</a></p>\n                <p class=\"list_article_p2\">[field:pubdate function=\"MyDate('Y-m-d ',@me)\" /]</p>\n            </div>\n			",1096,1403);
$z[3][4]['pagesize']="10";
$z[4]=Array("include","",1435,1472);
$z[4][4]['filename']="footer.htm";

?>