<?php
$z[0]=Array("include","",2991,3026);
$z[0][4]['filename']="head.htm";
$z[1]=Array("global","",3314,3341);
$z[1][4]['name']="cfg_basehost";
$z[2]=Array("global","",3421,3448);
$z[2][4]['name']="cfg_basehost";
$z[3]=Array("global","",3525,3552);
$z[3][4]['name']="cfg_basehost";
$z[4]=Array("global","",3629,3656);
$z[4][4]['name']="cfg_basehost";
$z[5]=Array("global","",3742,3769);
$z[5][4]['name']="cfg_basehost";
$z[6]=Array("include","",19565,19602);
$z[6][4]['filename']="footer.htm";

?>