<?php
$z[0]=Array("include","",2918,2953);
$z[0][4]['filename']="head.htm";
$z[1]=Array("global","",3230,3257);
$z[1][4]['name']="cfg_basehost";
$z[2]=Array("global","",3336,3363);
$z[2][4]['name']="cfg_basehost";
$z[3]=Array("global","",3439,3466);
$z[3][4]['name']="cfg_basehost";
$z[4]=Array("global","",3542,3569);
$z[4][4]['name']="cfg_basehost";
$z[5]=Array("global","",3654,3681);
$z[5][4]['name']="cfg_basehost";
$z[6]=Array("include","",20847,20884);
$z[6][4]['filename']="footer.htm";

?>