<?php  exit();
/*
Page: /plus/count.php?view=yes&aid=11&mid=1
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2010-09-23 04:41:54
*/
?>
<?php  exit();
/*
Page: /plus/count.php?view=yes&aid=11&mid=1
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2010-09-23 04:44:31
*/
?>
<?php  exit();
/*
Page: /plus/count.php?view=yes&aid=11&mid=1
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2010-09-23 06:47:48
*/
?>
